# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kipNfUFzio0YVJkj4X4Vuaapy2AJMl8B
"""

import pandas as pd
# 1. DataFrame yaratish
data={
    'Ism':['Ismoiljon', 'Jamshid','Abduraxmon','Boburjon','Izzatbek','Asadbek','Raximberdi','Ortiqmirzo','Sunatbek','Biloldin'],
    'Yoshi':[19,19,19,19,19,19,19,19,19,19],
    'Shahar':['Andijon','Namangan','Fargona','Andijon','Fargona','Fargona','Andijon','Andijon','Navoiy','Fargona']
}
df=pd.DataFrame(data)

# 2. Ma'lumotlarni ko'rish
print(df)

#3. Filtrlash
young_people = df[df['Yoshi']< 30]
print("30 yoshdan kichiklar:\n",young_people)

#4. O'zgartirish
df['Yoshi'] += 1 # Har bir shaxsning yoshini 1 ga oshirish
print("Yangilangan DataFrame :\n",df)
# 5.Fargonalilar
Manzil=df[df['Shahar'] =='Fargona']
print("Fargona :\n",Manzil)